### ISSUE TITLE
How do you train/transfer learn on your own 3D images?

### ISSUE THREAD

**Issue by saskra** [volume-em/empanada#12]
Thanks for publishing this, it looks like a great project to me! However, I have tested the provided model in Napari on my data and so far the results don't look as good as my old model for which I did transfer learning with CellPose. But I could imagine that there is more potential here if I do the transfer learning on a model that has already been trained on other mitochondria. Unfortunately, I have only found examples of what the configuration files for training can look like, but nothing about what I then need to do with these files: https://empanada.readthedocs.io/en/latest/tutorial/config.html#training Will there perhaps be more detailed instructions to follow?

**Comment by conradry** [comment]
Yes, tutorials are in the works. The napari plugin will get a substantial update in the next week or so that allows finetuning and training models from scratch. I'm also working to fill out the documentation for empanada (i.e., this library outside of the napari plugin) for anyone who prefers scripts to the GUI.

I'll give you a heads up in this thread as soon as it's ready.
