### ISSUE TITLE
Download model from dropbox

### ISSUE THREAD

**Issue by romainGuiet** [volume-em/empanada#15]
Hi @team,

I just noticed the model is downloaded from a dropbox 

``` 
from .autonotebook import tqdm as notebook_tqdm
Downloading: "https://www.dropbox.com/s/crp3jhr55ie3d3s/MitoNet_v2.pth?dl=1" to /home/jovyan/.empanada/MitoNet_v2.pth
100%|211M/211M [00:08<00:00, 25.2MB/s]
```
it would be nice to have it hosted on a "more" permanent repo, like zenodo maybe?

Cheers,

Romain

**Comment by conradry** [comment]
The models are available on [Zenodo](https://zenodo.org/record/6861565#.YtqOJS-cbTQ). For the Napari plugin I switched the link to DropBox because download speeds were occasionally very slow (like 10-15 minutes to download a 200 MB file). I actually moved the links used by the plugin back to Zenodo a few days ago. That change will take effect when I release the next update.
